project:
  type: website

website:
  title: "blog.mmolina.me"
  site-url: https://blog.mmolina.me
  favicon: assets/favicon.svg

  # SEO
  open-graph: true
  twitter-card: true
  
  # Components
  bread-crumbs: false
  search: 
    location: sidebar
    type: overlay
  sidebar:
    style: "floating"
    contents: auto
    logo: 'assets/logo.svg'
    logo-alt: Mateus Molina
  page-footer:
    center:
      - text: By <a href="https://mmolina.me">Mateus Molina</a>, unless otherwise stated.
      - icon: github
        href: https://github.com/MateusMolina
        aria-label: GitHub/MateusMolina
      - icon: rss
        href: index.xml
        aria-label: RSS Blog
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true