project:
  type: website
  output-dir: docs

date-format: iso

execute:
  freeze: auto

website:
  title: "blog.mmolina.me"
  site-url: https://blog.mmolina.me
  favicon: assets/favicon.svg

  # SEO
  open-graph: true
  twitter-card: true

  # Components
  bread-crumbs: false
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: "floating"
    contents:
      - text: About me
        href: about.qmd
      - text: Publications
        href: publications.qmd
      - text: "ML Safety Playbook"
        href: https://mlsafety.mmolina.me
      - section: "Posts"
        href: index.qmd
        contents:
          - text: Essays
            href: index.qmd#category=essay
          - text: Researches
            href: index.qmd#category=research
          - text: Reviews
            href: index.qmd#category=review
          - text: Org
            href: index.qmd#category=org
          - text: Guides
            href: index.qmd#category=guide
          - text: PhD
            href: index.qmd#category=phd
    logo: "assets/logo.svg"
    logo-alt: Mateus Molina
  page-footer:
    center:
      - text: By <a href="https://mmolina.me">Mateus Molina</a>, unless otherwise stated.
      - icon: github
        href: https://github.com/MateusMolina
        aria-label: GitHub/MateusMolina
      - icon: rss
        href: index.xml
        aria-label: RSS Blog
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

resources:
  - CNAME